name: PGFduel
version: beta 1.0.0
api-version: 1.16
author: CrimsonDart
main: net.pgfmc.duel.Main
commands:
  duelStart:
    description: Begins a duel
    usage: /duel
    permission: Duels.duelStart
    aliases: [duel, duelaccept, da]