name: PGFduels
version: alpha 1.1.1
api-version: 1.16
author: CrimsonDart
main: tk.pgfriends.duel.Main
commands:
  duelStart:
    description: Begins a duel
    usage: /duel
    permission: Duels.duelStart
    aliases: [duel, duelaccept, da]