name: PGFduel
version: beta 1.4.0
api-version: 1.16
author: CrimsonDart
main: net.pgfmc.duel.Main
description: implements the duel system into PGF
commands:
  #duelStart:
    #description: Begins a duel
    #usage: /duel
    #permission: Duels.duelStart
    #aliases: [duel, duelaccept, da]
  scoreOfWins:
    description: Gets the amount of wins of all players on the server
    usage: /scoreOfWins
    permission: Duels.scoreOfWins
    aliases: [SOW, Wins, duelWs]
  scoreOfLosses:
    description: Gets the amount of losses of all players on the server
    usage: /scoreOfLosses
    permission: Duels.scoreOfLosses
    aliases: [SOL, Losses, duelLs]